name: Hexo Blog CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Hexo
        run: |
          git clone https://github.com/${{ secrets.USER }}/${{ secrets.NAME }}
          sudo npm install hexo-cli -g
          hexo init blog
          rm blog/_config.landscape.yml
          rm blog/_config.yml
          rm blog/package.json
          rm blog/scaffolds/*
          rm blog/source/_posts/*
          mv ${{ secrets.NAME }}/_config.landscape.yml blog
          mv ${{ secrets.NAME }}/_config.yml blog
          mv ${{ secrets.NAME }}/package.json blog
          mv ${{ secrets.NAME }}/scaffolds/* blog/scaffolds
          mv ${{ secrets.NAME }}/source/_posts/* blog/source/_posts/*
          cd blog/themes
          git clone ${{ secrets.THEME }}
          cd ../
          npm install ${{ secrets.NPM }} --save
          hexo d
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
         personal_token: ${{ secrets.TOKEN }}
         publish_dir: ./public
         external_repository: ${{ secrets.USER }}/${{ secrets.DEPLAYNAME }}
         publish_branch: master
