name: CI Hexo Blog Deploy First

on:
  push:
    branches:
      - master

jobs:
  Deploy-Pages:
    name: Deploy Hexo Public To Pages
    runs-on: ubuntu-latest

    steps:
      # check it to your workflow can access it
      # from: https://github.com/actions/checkout
      - name: Checkout Repository master branch
        uses: actions/checkout@master

      - name: Setup Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: "10.x"

      - name: Setup Git Infomation
        run: |
          git config --global user.name 'CI' 
          git config --global user.email 'CI@ci.com'

      - name: Get Latest Commit Message
        run: |
          git log --pretty=format:"%s from Github Actions at `date +"%Y-%m-%d %H:%M:%S"`" --date=short -n 1  > commit-message.log

      - name: Setup Hexo Dependencies
        run: |
          npm install hexo-cli -g
          npm install

      - name: Generate public files
        run: |
          git clone https://github.com/${{ secrets.USER }}/${{ secrets.NAME }}
          sudo npm install hexo-cli -g
          hexo init blog
          rm blog/_config.landscape.yml
          rm blog/_config.yml
          rm blog/package.json
          rm blog/scaffolds/*
          rm blog/source/_posts/*
          mv ${{ secrets.NAME }}/_config.landscape.yml blog
          mv ${{ secrets.NAME }}/_config.yml blog
          mv ${{ secrets.NAME }}/package.json blog
          mv ${{ secrets.NAME }}/scaffolds/* blog/scaffolds
          mv ${{ secrets.NAME }}/source/_posts/* blog/source/_posts/*
          cd blog
          npm ${{ secrets.NPM }} --save
          hexo g

      - name: Deploy To Github Pages
        env:
          Github_Pages: ${{ secrets.DEPLAY }}
          Github_Token: ${{ secrets.API }}
        run: |
          mv .git/ ./public/
          cd ./public/
          git add .
          git commit -F ../commit-message.log
          git push --force --quiet "https://${Github_Token}@${Github_Pages}" master:master
