name: ActionsAutoHexo

on:
  push:
    branches:
      - master

jobs:
  Deploy-Pages:
    name: Actions Deploy Hexo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@master

      - name: Setup Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: "10.x"

      - name: Setup Hexo Dependencies
        run: |
          npm install hexo-cli -g
          npm install
      - name: Generate public files
        run: |
          git clone https://github.com/${{ secrets.CONFIG }}
          sudo npm install hexo-cli -g
          hexo init blog
          rm ./blog/_config.landscape.yml
          rm ./blog/_config.yml
          rm ./blog/package.json
          rm ./blog/scaffolds/*
          rm ./blog/source/_posts/*
          mv ./${NAME}/_config.landscape.yml ./blog
          mv ./${NAME}/_config.yml ./blog
          mv ./${NAME}/package.json ./blog
          mv ./${NAME}/scaffolds/* ./blog/scaffolds
          mv ./${NAME}/source/_posts/* ./blog/source/_posts/
          cd blog/themes
          git clone ${{ secrets.THEMES }}
          hexo g
          cd ../
          ${{ secrets.A }}
          rm .gitignore
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.API }}
          external_repository: ${{ secrets.DEPLOY }}
          publish_branch: master
          publish_dir: ./blog/public/
